package sysdig

const (
	SchemaIDKey             = "id"
	SchemaPoliciesKey       = "policies"
	SchemaPolicyIDsKey      = "policy_ids"
	SchemaNameKey           = "name"
	SchemaTypeKey           = "type"
	SchemaKindKey           = "kind"
	SchemaDescriptionKey    = "description"
	SchemaVersionKey        = "version"
	SchemaLinkKey           = "link"
	SchemaAuthorsKey        = "authors"
	SchemaAuthorKey         = "author"
	SchemaLastModifiedBy    = "last_modified_by"
	SchemaLastUpdated       = "last_updated"
	SchemaIsSystem          = "is_system"
	SchemaPublishedDateKey  = "published_date"
	SchemaMinKubeVersionKey = "min_kube_version"
	SchemaMaxKubeVersionKey = "max_kube_version"
	SchemaIsCustomKey       = "is_custom"
	SchemaIsActiveKey       = "is_active"
	SchemaPlatformKey       = "platform"
	SchemaZonesKey          = "zones"
	SchemaScopeKey          = "scope"
	SchemaScopesKey         = "scopes"
	SchemaTargetTypeKey     = "target_type"
	SchemaRulesKey          = "rules"
)
