package sysdig

const (
	SchemaIDKey             = "id"
	SchemaTeamIDKey         = "team_id"
	SchemaPoliciesKey       = "policies"
	SchemaPolicyIDsKey      = "policy_ids"
	SchemaNameKey           = "name"
	SchemaTypeKey           = "type"
	SchemaKindKey           = "kind"
	SchemaDescriptionKey    = "description"
	SchemaVersionKey        = "version"
	SchemaLinkKey           = "link"
	SchemaAuthorsKey        = "authors"
	SchemaAuthorKey         = "author"
	SchemaLastModifiedBy    = "last_modified_by"
	SchemaLastUpdated       = "last_updated"
	SchemaExpirationDateKey = "expiration_date"
	SchemaPublishedDateKey  = "published_date"
	SchemaCreatedDateKey    = "date_created"
	SchemaMinKubeVersionKey = "min_kube_version"
	SchemaMaxKubeVersionKey = "max_kube_version"
	SchemaIsCustomKey       = "is_custom"
	SchemaIsActiveKey       = "is_active"
	SchemaPlatformKey       = "platform"
	SchemaZonesKey          = "zones"
	SchemaZonesIDsKey       = "zone_ids"
	SchemaAllZones          = "all_zones"
	SchemaScopeKey          = "scope"
	SchemaScopesKey         = "scopes"
	SchemaTargetTypeKey     = "target_type"
	SchemaRoleKey           = "role"
	SchemaSystemRoleKey     = "system_role"
	SchemaRulesKey          = "rules"
	SchemaApiKeyKey         = "api_key"
)
