name: Terraform Provider Docs

on:
  pull_request:
    branches:
    - master

env:
  TERRAFORM_VERSION: "0.14.8"

jobs:
  ci-provider-docs:
    name: go build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
        terraform_wrapper: false

    - name: provider-docs check
      run: make provider-docs
