name: Scheduled Backend - Regresion Test

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

env:
  GO_VERSION: "^1.19"         # any 1.x version, see go.mod file for minimum

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  slackNotification:
    needs: test
    if: ${{ failure() }}
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      # https://github.com/8398a7/action-slack/blob/master/docs/content/usage/with.md
      - uses: 8398a7/action-slack@v3
        with:
          status: 'Failure'
          channel: '#terraform-provider'
          author_name: github-action
          title: 'Terraform Provider'
          text: 'Regression Test Failed, please take a look if you are a codeowner'
          fields: workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
