name: Scheduled Backend - Regresion Test

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

env:
  GO_VERSION: "^1.19"         # any 1.x version, see go.mod file for minimum

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Get dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          go mod tidy

      - name: Test
        run: make test

      - name: Acceptance tests
        run: make testacc
        env:
          SYSDIG_MONITOR_API_TOKEN: ${{ secrets.KUBELAB_MONITOR_API_TOKEN }}
          SYSDIG_SECURE_API_TOKEN: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}

  slackNotification:
    needs: test
    if: ${{ failure() }}
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ws-cloudnative-alerts
          SLACK_ICON: ':bell:'
          SLACK_COLOR: '#ff0000'
          SLACK_MESSAGE: 'Terraform Provider'
          SLACK_TITLE: 'Regression Test Failed, please take a look if you are a codeowner'
          SLACK_USERNAME: terraform-provider-sysdig
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
      # https://github.com/8398a7/action-slack/blob/master/docs/content/usage/with.md
      - uses: 8398a7/action-slack@v3
        with:
          status: 'Failure'
          channel: ' #ws-cloudnative-alerts'
          author_name: github-action
          title: 'Terraform Provider'
          text: 'Regression Test Failed, please take a look if you are a codeowner'
          fields: repo,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
