name: Scheduled Backend - Regresion Test

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

env:
  GO_VERSION: "^1.19"         # any 1.x version, see go.mod file for minimum

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Test
        run: make test

  test-sysdig:
    name: Test Sysdig
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Acceptance tests Sysdig
        run: make testacc
        env:
          SYSDIG_MONITOR_API_TOKEN: ${{ secrets.KUBELAB_MONITOR_API_TOKEN }}
          SYSDIG_SECURE_API_TOKEN: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}

  test-ibm:
    name: Test IBM
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Acceptance tests IBM
        run: make testacc-ibm
        env:
          SYSDIG_IBM_MONITOR_API_KEY: ${{ secrets.TERRAFORM_IBM_API_KEY }}
          SYSDIG_IBM_MONITOR_INSTANCE_ID: ${{ secrets.TERRAFORM_IBM_MONITOR_INSTANCE_ID }}
          SYSDIG_IBM_MONITOR_URL: "https://us-south.monitoring.test.cloud.ibm.com"
          SYSDIG_IBM_MONITOR_IAM_URL: "https://iam.test.cloud.ibm.com"

  slackNotification:
    needs: [test, test-sysdig, test-ibm]
    if: ${{ failure() }}
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      # https://github.com/8398a7/action-slack/blob/master/docs/content/usage/with.md
      - uses: 8398a7/action-slack@v3
        with:
          status: 'Failure'
          channel: '#terraform-provider'
          author_name: github-action
          title: 'Terraform Provider'
          text: 'Regression Test Failed, please take a look if you are a codeowner'
          fields: workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
