name: Scheduled Backend - Regresion Test

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

env:
  GO_VERSION: "^1.19"         # any 1.x version, see go.mod file for minimum

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Get dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          go mod tidy

      - name: Test
        run: make test

      - name: Acceptance tests
        run: make testacc
        env:
          SYSDIG_MONITOR_API_TOKEN: ${{ secrets.KUBELAB_MONITOR_API_TOKEN }}
          SYSDIG_SECURE_API_TOKEN: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}

  slackNotification:
    needs: test
    if: needs.test.result == 'failed'
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ws-cloudnative-alerts
          SLACK_ICON: https://github.com/fluidicon.png
          SLACK_MESSAGE: 'Terraform Provider'
          SLACK_TITLE: Regression Test Failed
          SLACK_USERNAME: terraform-provider-sysdig
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,action,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
