name: Scheduled Backend - Regresion Test

on:
  schedule:
    - cron: "0 11 * * *"

env:
  GO_VERSION: "^1.19"         # any 1.x version, see go.mod file for minimum

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Get dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          go mod tidy

      - name: Test
        run: make test

      - name: Acceptance tests
        run: make testacc
        env:
          SYSDIG_MONITOR_API_TOKEN: ${{ secrets.KUBELAB_MONITOR_API_TOKEN }}
          SYSDIG_SECURE_API_TOKEN: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}

  slackNotification:
    if: failure()
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ws-cloudnative-alerts
          SLACK_ICON: https://github.com/fluidicon.png
          SLACK_MESSAGE: 'Terraform Provider Regression Test Failed'
          SLACK_TITLE: Terraform Provider - Regression Test Failed
          SLACK_USERNAME: gitHub
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
