name: CI - Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
    branches:
      - master

jobs:
  build-multiarch:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop --command bash -e {0}
    strategy:
      matrix:
        include:
          - os: darwin
            arch: amd64
          - os: freebsd
            arch: 386
          - os: freebsd
            arch: amd64
          - os: freebsd
            arch: arm
          - os: linux
            arch: 386
          - os: linux
            arch: amd64
          - os: linux
            arch: arm
          - os: openbsd
            arch: 386
          - os: openbsd
            arch: amd64
          - os: solaris
            arch: amd64
          - os: windows
            arch: 386
          - os: windows
            arch: amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Set up Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@908b263ff629f4cc17666315b7fd3ec127c6244d # v14

      - name: Build project
        run: GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o terraform-provider-sysdig

  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
