name: IBM terraform acceptance tests

on:
  workflow_call:
    secrets:
      api-key:
        required: true
      instance-id:
        required: true
jobs:
  test-ibm:
    name: Test IBM
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Acceptance tests IBM
        run: make testacc-ibm
        env:
          SYSDIG_IBM_MONITOR_API_KEY: ${{ secrets.api-key }}
          SYSDIG_IBM_MONITOR_INSTANCE_ID: ${{ secrets.instance-id }}
          SYSDIG_IBM_MONITOR_URL: "https://us-south.monitoring.test.cloud.ibm.com"
          SYSDIG_IBM_MONITOR_IAM_URL: "https://iam.test.cloud.ibm.com"
