on:
  issues:
    types: [opened]
name: Issue created Slack Notification
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ws-cloudnative-alerts
          SLACK_ICON: https://github.com/fluidicon.png
          SLACK_MESSAGE: 'Terraform Provider'
          SLACK_TITLE: A new issue was created
          SLACK_USERNAME: terraform-provider-sysdig
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: true
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: message,author,ref
        env:
          SLACK_WEBHOOK_URL: {{ secrets.SLACK_WEBHOOK }}