name: Sysdig terraform acceptance tests

on:
  workflow_call:
    secrets:
      monitor-api-token:
        required: true
      secure-api-token:
        required: true

jobs:
  test-sysdig:
    name: Test Sysdig
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Acceptance tests Sysdig
        run: make testacc
        env:
          SYSDIG_MONITOR_API_TOKEN: ${{ secrets.monitor-api-token }}
          SYSDIG_SECURE_API_TOKEN: ${{ secrets.secure-api-token }}
